### ISSUE TITLE
Nested media queries

### ISSUE THREAD

**Issue by dyatko** [NV/CSSOM#104]
I'm running tests using latest jest and jsdom fails due to "Could not parse CSS stylesheet"

```
jest: 24.9.0
jsdom: 15.2.1
cssom: 0.4.2
```

The issue is with inherited media queries which work perfectly in Chrome.

```css
@media (min-width: 768px) {
  h1 {
    color: red;
  }

  @media (min-resolution: 0.001dpcm) {
    h1 {
      color: yellow;
    }

    @supports (-webkit-appearance: none) {
      h1 {
        color: green;
      }
    }
  }
}

@media (min-resolution: 0.001dpcm) {
  a {
    color: green;
  }
}

@supports (-webkit-appearance: none) {
  p {
    color: blue;
  }
}
```

```html
<h1>Hello!</h1>
<p>
  Inherited media queries <a href="#">here</a>.
</p>
```
