### ISSUE TITLE
Support duplicate properties

### ISSUE THREAD

**Issue by rstacruz** [NV/CSSOM#43]
This is useful in sheets that use CSS3, say for example this:

``` css
div {
  background: -moz-linear-gradient(x);
  background: -webkit-linear-gradient(x);
  background: linear-gradient(x);
}
```

Gets you this `styles` structure:

``` js
{ '0': 'background',
  length: 1,
  parentRule: 
   { parentRule: null,
     parentStyleSheet: { parentStyleSheet: null, cssRules: [Object] },
     selectorText: 'div',
     style: [Circular],
     __starts: 0,
     __ends: 122 },
  _importants: { background: '' },
  __starts: 4,
  background: 'linear-gradient(x)' }
```

...which is less than ideal. Notice that the `length` is `1` and that the only `background` it knows about is the last one.
