### ISSUE TITLE
@keyframes bug

### ISSUE THREAD

**Issue by aui** [NV/CSSOM#80]
``` css
@keyframes myfirst {
    from {background: red;}
    to {background: yellow;}
}
```

bug: http://nv.github.io/CSSOM/docs/parse.html#css=%40keyframes%20test%20%7B%0A%20%20%20%20from%20%7Bbackground%3A%20red%3B%7D%0A%20%20%20%20to%20%7Bbackground%3A%20yellow%3B%7D%0A%7D
