### ISSUE TITLE
should not remove spaces in calc() function

### ISSUE THREAD

**Issue by jonkemp** [NV/CSSOM#86]
Spaces are mandatory inside CSS [`calc()`](https://developer.mozilla.org/en/docs/Web/CSS/calc) function, and should not be removed in inlining.

```css
.foo {
  width: calc(100% - 80px);
}
```

gets parsed to this
```css
.foo {width: calc(100%-80px);}
```

and that doesn't work in the browser.

linear-gradient also has the same issue.

`linear-gradient(135deg, #00689b 0%, #00375a 90%, #00375a 90%, #003455 100%);`

gets parsed to this

`linear-gradient(135deg, #00689b0%, #00375a90%, #00375a90%, #003455100%);`
